server:
  #应用端口
  port: 18892
spring:
  datasource:
    url: jdbc:mysql://47.98.202.59/electric_room?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  data:
    mongodb:
      host: 47.98.202.59
      database: device_data
  redis:
    host: 47.98.202.59
    database: 3
    password: 1012xiao

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
